import mongoose from "mongoose";
import dotenv from "dotenv";
import Destination from "./src/models/Destination.js";

dotenv.config();

const destinations = [
  {
    name: "Bali",
    country: "Indonesia",
    city: "Bali",
    region: "asia",
    vibe: "beach",
    budget: "low",
    climateType: "tropical",
    tripTypes: ["solo", "couple", "friends"],
    activityLevel: "moderate",
    avgDailyCost: 40,
    popularity: 95,
    featured: true,
    tags: ["surf", "spa", "nature", "temples", "beach", "relaxation"],
    categories: ["relaxation", "adventure", "nature"],
    description: "Tropical paradise with beaches and culture."
  },
  {
    name: "Tokyo",
    country: "Japan",
    city: "Tokyo",
    region: "asia",
    vibe: "city",
    budget: "high",
    climateType: "temperate",
    tripTypes: ["solo", "friends", "couple"],
    avgDailyCost: 110,
    popularity: 97,
    featured: true,
    tags: ["technology", "food", "anime", "culture", "city"],
    categories: ["city", "cultural", "food"],
    description: "A fast-paced city blending modern life and tradition."
  },
  {
    name: "Kyoto",
    country: "Japan",
    city: "Kyoto",
    region: "asia",
    vibe: "cultural",
    budget: "mid",
    climateType: "temperate",
    tripTypes: ["solo", "couple", "family"],
    avgDailyCost: 80,
    popularity: 91,
    featured: true,
    tags: ["temples", "culture", "history", "gardens"],
    categories: ["cultural", "history", "relaxation"],
    description: "Historic temples, gardens, and traditional Japanese culture."
  },
  {
    name: "Seoul",
    country: "South Korea",
    city: "Seoul",
    region: "asia",
    vibe: "city",
    budget: "mid",
    climateType: "temperate",
    tripTypes: ["solo", "friends", "couple"],
    avgDailyCost: 75,
    popularity: 92,
    featured: true,
    tags: ["k-pop", "food", "shopping", "technology", "nightlife"],
    categories: ["city", "food", "cultural"],
    description: "A modern city known for food, shopping, music, and nightlife."
  },
  {
    name: "Bangkok",
    country: "Thailand",
    city: "Bangkok",
    region: "asia",
    vibe: "city",
    budget: "low",
    climateType: "tropical",
    tripTypes: ["solo", "friends"],
    avgDailyCost: 35,
    popularity: 93,
    featured: true,
    tags: ["food", "nightlife", "temples", "city"],
    categories: ["city", "food", "cultural"],
    description: "A budget-friendly city with street food, temples, and nightlife."
  },
  {
    name: "Phuket",
    country: "Thailand",
    city: "Phuket",
    region: "asia",
    vibe: "beach",
    budget: "mid",
    climateType: "tropical",
    tripTypes: ["couple", "friends", "family"],
    avgDailyCost: 60,
    popularity: 90,
    featured: true,
    tags: ["beach", "island", "nightlife", "snorkeling"],
    categories: ["beach", "relaxation", "adventure"],
    description: "A popular island destination with beaches and clear water."
  },
  {
    name: "Singapore",
    country: "Singapore",
    city: "Singapore",
    region: "asia",
    vibe: "city",
    budget: "high",
    climateType: "tropical",
    tripTypes: ["solo", "family", "couple"],
    avgDailyCost: 120,
    popularity: 91,
    featured: true,
    tags: ["city", "food", "shopping", "gardens"],
    categories: ["city", "food", "luxury"],
    description: "A clean modern city with gardens, food markets, and shopping."
  },
  {
    name: "Dubai",
    country: "UAE",
    city: "Dubai",
    region: "asia",
    vibe: "luxury",
    budget: "high",
    climateType: "hot",
    tripTypes: ["family", "couple", "friends"],
    avgDailyCost: 150,
    popularity: 90,
    featured: true,
    tags: ["shopping", "desert", "luxury", "city"],
    categories: ["luxury", "city"],
    description: "Known for luxury shopping, skyscrapers, and desert experiences."
  },
  {
    name: "Paris",
    country: "France",
    city: "Paris",
    region: "europe",
    vibe: "city",
    budget: "high",
    climateType: "temperate",
    tripTypes: ["couple", "friends", "solo"],
    avgDailyCost: 120,
    popularity: 98,
    featured: true,
    tags: ["romance", "art", "food", "culture", "city"],
    categories: ["cultural", "luxury", "city"],
    description: "Famous for romance, art, fashion, and food."
  },
  {
    name: "Rome",
    country: "Italy",
    city: "Rome",
    region: "europe",
    vibe: "cultural",
    budget: "mid",
    climateType: "temperate",
    tripTypes: ["couple", "family", "solo"],
    avgDailyCost: 80,
    popularity: 94,
    featured: true,
    tags: ["history", "food", "architecture", "culture"],
    categories: ["cultural", "city", "food"],
    description: "Historic city known for architecture, food, and ancient landmarks."
  },
  {
    name: "Venice",
    country: "Italy",
    city: "Venice",
    region: "europe",
    vibe: "romantic",
    budget: "high",
    climateType: "temperate",
    tripTypes: ["couple", "solo"],
    avgDailyCost: 115,
    popularity: 89,
    featured: true,
    tags: ["canals", "romance", "history", "architecture"],
    categories: ["romantic", "cultural", "city"],
    description: "A romantic canal city with beautiful architecture."
  },
  {
    name: "Barcelona",
    country: "Spain",
    city: "Barcelona",
    region: "europe",
    vibe: "beach",
    budget: "mid",
    climateType: "sunny",
    tripTypes: ["friends", "couple", "solo"],
    avgDailyCost: 70,
    popularity: 92,
    featured: true,
    tags: ["beach", "food", "nightlife", "city"],
    categories: ["city", "beach", "food"],
    description: "A lively destination mixing beaches, food, and nightlife."
  },
  {
    name: "Madrid",
    country: "Spain",
    city: "Madrid",
    region: "europe",
    vibe: "cultural",
    budget: "mid",
    climateType: "sunny",
    tripTypes: ["solo", "friends", "couple"],
    avgDailyCost: 70,
    popularity: 88,
    featured: false,
    tags: ["museums", "food", "culture", "shopping"],
    categories: ["city", "cultural", "food"],
    description: "Spain's capital, full of museums, restaurants, and plazas."
  },
  {
    name: "Amsterdam",
    country: "Netherlands",
    city: "Amsterdam",
    region: "europe",
    vibe: "city",
    budget: "mid",
    climateType: "temperate",
    tripTypes: ["friends", "couple", "solo"],
    avgDailyCost: 85,
    popularity: 90,
    featured: true,
    tags: ["canals", "culture", "cycling", "city"],
    categories: ["cultural", "city"],
    description: "A charming city known for canals, cycling, and culture."
  },
  {
    name: "Santorini",
    country: "Greece",
    city: "Santorini",
    region: "europe",
    vibe: "romantic",
    budget: "high",
    climateType: "sunny",
    tripTypes: ["couple"],
    avgDailyCost: 130,
    popularity: 93,
    featured: true,
    tags: ["romance", "sunset", "luxury", "island", "beach"],
    categories: ["beach", "luxury", "relaxation"],
    description: "A romantic island destination with sunsets and sea views."
  },
  {
    name: "Athens",
    country: "Greece",
    city: "Athens",
    region: "europe",
    vibe: "cultural",
    budget: "mid",
    climateType: "sunny",
    tripTypes: ["solo", "friends", "family"],
    avgDailyCost: 65,
    popularity: 87,
    featured: false,
    tags: ["history", "ancient", "food", "culture"],
    categories: ["cultural", "history", "city"],
    description: "A historic city known for ancient landmarks and Greek food."
  },
  {
    name: "London",
    country: "United Kingdom",
    city: "London",
    region: "europe",
    vibe: "city",
    budget: "high",
    climateType: "temperate",
    tripTypes: ["solo", "friends", "family", "couple"],
    avgDailyCost: 125,
    popularity: 96,
    featured: true,
    tags: ["museums", "shopping", "history", "city"],
    categories: ["city", "cultural"],
    description: "A major city with museums, landmarks, shopping, and theatre."
  },
  {
    name: "Edinburgh",
    country: "United Kingdom",
    city: "Edinburgh",
    region: "europe",
    vibe: "cultural",
    budget: "mid",
    climateType: "cold",
    tripTypes: ["solo", "couple", "friends"],
    avgDailyCost: 85,
    popularity: 85,
    featured: false,
    tags: ["castle", "history", "old town", "culture"],
    categories: ["cultural", "history", "city"],
    description: "A historic Scottish city with castles, festivals, and old streets."
  },
  {
    name: "Iceland",
    country: "Iceland",
    city: "Reykjavik",
    region: "europe",
    vibe: "nature",
    budget: "high",
    climateType: "cold",
    tripTypes: ["couple", "friends"],
    avgDailyCost: 140,
    popularity: 88,
    featured: true,
    tags: ["nature", "northern lights", "adventure", "scenery"],
    categories: ["nature", "adventure"],
    description: "Ideal for scenic landscapes, nature, and outdoor adventure."
  },
  {
    name: "New York",
    country: "USA",
    city: "New York",
    region: "americas",
    vibe: "city",
    budget: "high",
    climateType: "cold",
    tripTypes: ["friends", "solo", "family"],
    avgDailyCost: 130,
    popularity: 96,
    featured: true,
    tags: ["shopping", "nightlife", "food", "city"],
    categories: ["city", "food"],
    description: "A world-famous urban destination with food, shopping, and nightlife."
  },
  {
    name: "Los Angeles",
    country: "USA",
    city: "Los Angeles",
    region: "americas",
    vibe: "beach",
    budget: "high",
    climateType: "sunny",
    tripTypes: ["friends", "solo", "couple"],
    avgDailyCost: 125,
    popularity: 91,
    featured: true,
    tags: ["hollywood", "beach", "shopping", "city"],
    categories: ["city", "beach", "luxury"],
    description: "A sunny city known for beaches, entertainment, and Hollywood."
  },
  {
    name: "Miami",
    country: "USA",
    city: "Miami",
    region: "americas",
    vibe: "beach",
    budget: "high",
    climateType: "tropical",
    tripTypes: ["friends", "couple"],
    avgDailyCost: 115,
    popularity: 89,
    featured: true,
    tags: ["beach", "nightlife", "food", "sun"],
    categories: ["beach", "city", "relaxation"],
    description: "A beach city with nightlife, warm weather, and Latin culture."
  },
  {
    name: "Toronto",
    country: "Canada",
    city: "Toronto",
    region: "americas",
    vibe: "city",
    budget: "high",
    climateType: "cold",
    tripTypes: ["solo", "friends", "family"],
    avgDailyCost: 105,
    popularity: 86,
    featured: false,
    tags: ["city", "food", "culture", "shopping"],
    categories: ["city", "cultural", "food"],
    description: "A diverse Canadian city with food, culture, and urban attractions."
  },
  {
    name: "Vancouver",
    country: "Canada",
    city: "Vancouver",
    region: "americas",
    vibe: "nature",
    budget: "high",
    climateType: "temperate",
    tripTypes: ["solo", "couple", "family"],
    avgDailyCost: 110,
    popularity: 87,
    featured: false,
    tags: ["mountains", "nature", "city", "coast"],
    categories: ["nature", "city", "adventure"],
    description: "A coastal city surrounded by mountains and outdoor activities."
  },
  {
    name: "Cancun",
    country: "Mexico",
    city: "Cancun",
    region: "americas",
    vibe: "beach",
    budget: "mid",
    climateType: "tropical",
    tripTypes: ["couple", "friends", "family"],
    avgDailyCost: 75,
    popularity: 90,
    featured: true,
    tags: ["beach", "resort", "snorkeling", "sun"],
    categories: ["beach", "relaxation"],
    description: "A tropical beach destination with resorts and clear water."
  },
  {
    name: "Mexico City",
    country: "Mexico",
    city: "Mexico City",
    region: "americas",
    vibe: "cultural",
    budget: "low",
    climateType: "temperate",
    tripTypes: ["friends", "solo"],
    avgDailyCost: 45,
    popularity: 86,
    featured: false,
    tags: ["food", "history", "culture", "city"],
    categories: ["cultural", "food", "city"],
    description: "A vibrant city full of history, food, and culture."
  },
  {
    name: "Rio de Janeiro",
    country: "Brazil",
    city: "Rio de Janeiro",
    region: "americas",
    vibe: "beach",
    budget: "mid",
    climateType: "tropical",
    tripTypes: ["friends", "couple", "solo"],
    avgDailyCost: 70,
    popularity: 88,
    featured: true,
    tags: ["beach", "music", "festival", "nature"],
    categories: ["beach", "city", "cultural"],
    description: "A colourful city known for beaches, mountains, and carnival energy."
  },
  {
    name: "Buenos Aires",
    country: "Argentina",
    city: "Buenos Aires",
    region: "americas",
    vibe: "cultural",
    budget: "mid",
    climateType: "temperate",
    tripTypes: ["solo", "couple", "friends"],
    avgDailyCost: 55,
    popularity: 84,
    featured: false,
    tags: ["tango", "food", "culture", "architecture"],
    categories: ["cultural", "city", "food"],
    description: "A stylish city famous for tango, architecture, and food."
  },
  {
    name: "Cape Town",
    country: "South Africa",
    city: "Cape Town",
    region: "africa",
    vibe: "nature",
    budget: "mid",
    climateType: "sunny",
    tripTypes: ["friends", "couple"],
    avgDailyCost: 65,
    popularity: 89,
    featured: true,
    tags: ["beach", "mountains", "wildlife", "nature"],
    categories: ["nature", "adventure", "beach"],
    description: "A scenic destination with beaches, mountains, and wildlife."
  },
  {
    name: "Marrakech",
    country: "Morocco",
    city: "Marrakech",
    region: "africa",
    vibe: "cultural",
    budget: "low",
    climateType: "hot",
    tripTypes: ["solo", "couple", "friends"],
    avgDailyCost: 45,
    popularity: 86,
    featured: true,
    tags: ["markets", "desert", "culture", "food"],
    categories: ["cultural", "food", "adventure"],
    description: "A colourful city with markets, gardens, food, and desert tours."
  },
  {
    name: "Cairo",
    country: "Egypt",
    city: "Cairo",
    region: "africa",
    vibe: "cultural",
    budget: "low",
    climateType: "hot",
    tripTypes: ["solo", "family", "friends"],
    avgDailyCost: 40,
    popularity: 87,
    featured: false,
    tags: ["pyramids", "history", "museum", "culture"],
    categories: ["cultural", "history", "city"],
    description: "A historic city close to the pyramids and ancient landmarks."
  },
  {
    name: "Sydney",
    country: "Australia",
    city: "Sydney",
    region: "oceania",
    vibe: "beach",
    budget: "high",
    climateType: "sunny",
    tripTypes: ["friends", "family", "solo"],
    avgDailyCost: 120,
    popularity: 91,
    featured: true,
    tags: ["beach", "city", "surf", "food"],
    categories: ["beach", "city"],
    description: "A coastal city famous for beaches, surfing, and landmarks."
  },
  {
    name: "Melbourne",
    country: "Australia",
    city: "Melbourne",
    region: "oceania",
    vibe: "city",
    budget: "high",
    climateType: "temperate",
    tripTypes: ["solo", "friends", "couple"],
    avgDailyCost: 105,
    popularity: 86,
    featured: false,
    tags: ["coffee", "art", "food", "city"],
    categories: ["city", "food", "cultural"],
    description: "A creative city known for coffee, art, food, and culture."
  },
  {
    name: "Auckland",
    country: "New Zealand",
    city: "Auckland",
    region: "oceania",
    vibe: "nature",
    budget: "high",
    climateType: "temperate",
    tripTypes: ["solo", "couple", "family"],
    avgDailyCost: 110,
    popularity: 84,
    featured: false,
    tags: ["nature", "harbour", "islands", "adventure"],
    categories: ["nature", "adventure", "city"],
    description: "A harbour city surrounded by islands, nature, and outdoor trips."
  }
];

try {
  await mongoose.connect(process.env.MONGO_URI);

  await Destination.deleteMany({});
  await Destination.insertMany(destinations);

  console.log(`Database seeded with ${destinations.length} destinations!`);
} catch (err) {
  console.error("Seed failed:", err);
} finally {
  await mongoose.disconnect();
  process.exit();
}